### ISSUE TITLE
About the installation of sonata

### ISSUE THREAD

**Issue by lzg38844037** [WISDEM/SONATA#13]
Dear Sir, hello, I want to use SONATA to calculate the 6×6 stiffness matrix of the blade, but at present, I have encountered some installation problems, when I install SONATA, the message is fatal: cannot read the remote warehouse, please confirm that you have the correct access permission and the warehouse exists, I would like to ask if you have any solution?

**Comment by ptrbortolotti** [comment]
what OS are you using?

**Comment by lzg38844037** [comment]
Thanks for your reply, I installed ubuntu on a VMware Workstation，Is it a problem with the system？

**Comment by lzg38844037** [comment]
Dear ptrbortolotti
 I have successfully installed SONATA, but failed to run IEA15 case, the error message is as follows.Is there any solution?
STATUS:	 Reading YAML Dictionary for slender composite structure: IEA 15MW Offshore Reference Turbine, with taped chord tip design
choose correct axes format: ref_axes_format = 0 (HT) or 1 (WT)
Traceback (most recent call last):
  File "/home/lig/anaconda3/anba8/SONATA/examples/0_beams/1_sonata_IEA15.py", line 59, in <module>
    job = Blade(name=job_name, filename=filename_str, flags=flags_dict, stations=radial_stations)  # initialize job with respective yaml input file
  File "/home/lig/anaconda3/envs/anba4-env/lib/python3.9/site-packages/SONATA-0.3.6-py3.9.egg/SONATA/classBlade.py", line 196, in __init__
    self.read_yaml(yml.get('components').get('blade'), airfoils, **kwargs)
  File "/home/lig/anaconda3/envs/anba4-env/lib/python3.9/site-packages/SONATA-0.3.6-py3.9.egg/SONATA/classBlade.py", line 508, in read_yaml
    (self.blade_ref_axis_BSplineLst, self.f_blade_ref_axis, tmp_blra) = self._read_ref_axes(yml_os.get('beam_geometric_curve'), ref_axes_format=kwargs.get('ref_axes_format'))
  File "/home/lig/anaconda3/envs/anba4-env/lib/python3.9/site-packages/SONATA-0.3.6-py3.9.egg/SONATA/classBlade.py", line 241, in _read_ref_axes
    f_ref_axis_x = interp1d(tmp_ra['x'][:,0], tmp_ra['x'][:,1], bounds_error=False, fill_value='extrapolate')

**Comment by ptrbortolotti** [comment]
Can you please confirm to be on the develop branch of the repo? Type `git status` or `git log` or `git branch`
